language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r spring-boot-blog-freelec *
  - mkdir -p deploy
  - mv spring-boot-blog-freelec.zip deploy/spring-boot-blog-freelec.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # set in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-build-freelec
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # private access to the zip file
    local_dir: deploy # dir set in before_deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # set in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-build-freelec
    key: spring-boot-blog-freelec.zip # pass build file
    bundle_type: zip
    application: spring-boot-blog-freelec # CodeDeploy application name
    deployment_group: spring-boot-blog-freelec-group
    region: ap-northeast-2
    wait-until-deployed: true


# Email when CI completed successfully
notifications:
  email:
    recipients:
      - jeonginlee0304@gmail.com