language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Home of Travis CI Server
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# Email when CI completed successfully
notifications:
  email:
    recipients:
      - jeonginlee0304@gmail.com